IF NOT EXISTS(SELECT * FROM sys.databases WHERE name = 'USERS')
BEGIN
CREATE DATABASE USERS
END;
GO
USE USERS;
GO
IF NOT EXISTS(SELECT * FROM sysobjects WHERE name = 'TEST' and xtype = 'U')
CREATE TABLE TEST (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Name VARCHAR(50) UNIQUE,
    Email VARCHAR(50),
    IsAdmin BIT
);
INSERT INTO "TEST" VALUES ('Bambus', 'bambik@gmail.com', 0)
SELECT * FROM "TEST";